In [1]:
#Set dependencies
import pandas as pd
import os
import numpy as np

sensors = ['42043','42044','42047','8764314','8770613', 'TABS-X']
monthsf = ['0617','0717','0817','0917']

hurricane = "Harvey"
year = 2017

files = []

#naming csv file for all resources
for i in sensors:
    for j in monthsf:
        files.append(f"../data/2017/{i}-{j}.csv")
        
print(len(files))

24

In [2]:
# Read all csv files into a list of dataframes
data = []
count = 0
for i in range(len(files)):    
    df = pd.read_csv(files[i])
    print(f'Reading csvfile {i}...{len(df)} records')
    count+=len(df)
    data.append(df)
        
df_data = pd.DataFrame(data) 
print()
print(f'There are a total of {count} records')
df_data.shape

Reading csvfile 0...763 records
Reading csvfile 1...0 records
Reading csvfile 2...440 records
Reading csvfile 3...455 records
Reading csvfile 4...1440 records
Reading csvfile 5...1485 records
Reading csvfile 6...1488 records
Reading csvfile 7...1440 records
Reading csvfile 8...1440 records
Reading csvfile 9...1487 records
Reading csvfile 10...465 records
Reading csvfile 11...0 records
Reading csvfile 12...622 records
Reading csvfile 13...733 records
Reading csvfile 14...634 records
Reading csvfile 15...664 records
Reading csvfile 16...622 records
Reading csvfile 17...734 records
Reading csvfile 18...634 records
Reading csvfile 19...666 records
Reading csvfile 20...1440 records
Reading csvfile 21...1488 records
Reading csvfile 22...1438 records
Reading csvfile 23...1440 records

There are a total of 22018 records

(24, 1)

In [3]:
# display any of the dataframes
df_data[0][0]

,Unnamed: 0,sensor,date,latitude,longitude,air_pressure(mBar),air_temperature,sea_water_practical_salinity,sea_water_temperature,wind_speed
0,0,ioos:station:wmo:42043:1,2017-06-07 00:00:00+00:00,28.9818,-94.9186,1006.28,26.6,0.02,29.05,1.552707
1,1,ioos:station:wmo:42043:1,2017-06-07 00:30:00+00:00,28.9818,-94.9186,1006.65,26.3,0.03,28.74,0.848999
2,2,ioos:station:wmo:42043:1,2017-06-07 01:00:00+00:00,28.9818,-94.9186,1006.68,25.9,0.03,28.17,0.869770
3,3,ioos:station:wmo:42043:1,2017-06-07 01:30:00+00:00,28.9818,-94.9186,1006.52,26.1,0.04,27.68,2.963798
4,4,ioos:station:wmo:42043:1,2017-06-07 02:00:00+00:00,28.9818,-94.9186,1006.60,26.0,0.04,27.52,2.997866
...,...,...,...,...,...,...,...,...,...,...
758,758,ioos:station:wmo:42043:1,2017-06-22 19:00:00+00:00,28.9818,-94.9186,1006.47,25.9,23.40,28.00,7.786886
759,759,ioos:station:wmo:42043:1,2017-06-22 19:30:00+00:00,28.9818,-94.9186,1006.68,26.1,22.91,28.03,7.897044
760,760,ioos:station:wmo:42043:1,2017-06-22 20:00:00+00:00,28.9818,-94.9186,1006.60,26.0,22.88,28.05,8.059460
761,761,ioos:station:wmo:42043:1,2017-06-22 20:30:00+00:00,28.9818,-94.9186,1006.24,26.1,24.40,28.01,7.207468
762,762,ioos:station:wmo:42043:1,2017-06-22 21:00:00+00:00,28.9818,-94.9186,1006.30,26.0,21.75,27.99,6.607851

In [4]:
# Merge all the dataframes into one complete dataframe
df_merge = pd.DataFrame()
for i in range(len(df_data)):
    df_merge = pd.concat([df_merge, df_data[0][i]], axis=0)

df_merge

,Unnamed: 0,sensor,date,latitude,longitude,air_pressure(mBar),air_temperature,sea_water_practical_salinity,sea_water_temperature,wind_speed
0,0,ioos:station:wmo:42043:1,2017-06-07 00:00:00+00:00,28.9818,-94.9186,1006.28,26.6,0.02,29.05,1.552707
1,1,ioos:station:wmo:42043:1,2017-06-07 00:30:00+00:00,28.9818,-94.9186,1006.65,26.3,0.03,28.74,0.848999
2,2,ioos:station:wmo:42043:1,2017-06-07 01:00:00+00:00,28.9818,-94.9186,1006.68,25.9,0.03,28.17,0.869770
3,3,ioos:station:wmo:42043:1,2017-06-07 01:30:00+00:00,28.9818,-94.9186,1006.52,26.1,0.04,27.68,2.963798
4,4,ioos:station:wmo:42043:1,2017-06-07 02:00:00+00:00,28.9818,-94.9186,1006.60,26.0,0.04,27.52,2.997866
...,...,...,...,...,...,...,...,...,...,...
1435,1435,ioos:station:TABS:X:1,2017-09-30 21:30:00+00:00,27.0660,-96.3383,1013.73,0.0,32.48,29.05,0.000000
1436,1436,ioos:station:TABS:X:1,2017-09-30 22:00:00+00:00,27.0660,-96.3383,1013.96,0.0,32.47,29.05,0.000000
1437,1437,ioos:station:TABS:X:1,2017-09-30 22:30:00+00:00,27.0660,-96.3383,1014.23,0.0,32.49,29.04,0.000000
1438,1438,ioos:station:TABS:X:1,2017-09-30 23:00:00+00:00,27.0660,-96.3383,1014.28,0.0,32.54,29.03,0.000000
1439,1439,ioos:station:TABS:X:1,2017-09-30 23:30:00+00:00,27.0660,-96.3383,1014.38,0.0,32.56,29.00,0.000000

In [5]:
#Set the file path to export city data
csvFile = os.path.join("../data",f"{hurricane}_{year}.csv")

#Export clean datframe to csv file
df_merge.to_csv(csvFile)
        
print(f'Export completed for {hurricane}_{year} ')

Export completed for Harvey_2017