In [2]:
#Set dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import gmaps
import os
from pprint import pprint
from scipy.stats import linregress
import scipy.stats as st
#from citypy import citipy


#import API key
from config import g_key

#import csv 
#Hurc_df= "..data/Harvey_2017.csv"

In [7]:
# Read the csv and the study results
csv_import = os.path.join("..", "data", "Harvey_2017.csv")
Hurc_df = pd.read_csv(csv_import)

# Combine the data into a single dataset
#combined_data = pd.merge(salinty_df, temp_results_df, on="Platform ID")

# Display the data table for preview
Hurc_df

,Unnamed: 0,Unnamed: 0.1,sensor,date,latitude,longitude,air_pressure(mBar),air_temperature,sea_water_practical_salinity,sea_water_temperature,wind_speed
0,0,0,ioos:station:wmo:42043:1,2017-06-07 00:00:00+00:00,28.9818,-94.9186,1006.28,26.6,0.02,29.05,1.552707
1,1,1,ioos:station:wmo:42043:1,2017-06-07 00:30:00+00:00,28.9818,-94.9186,1006.65,26.3,0.03,28.74,0.848999
2,2,2,ioos:station:wmo:42043:1,2017-06-07 01:00:00+00:00,28.9818,-94.9186,1006.68,25.9,0.03,28.17,0.869770
3,3,3,ioos:station:wmo:42043:1,2017-06-07 01:30:00+00:00,28.9818,-94.9186,1006.52,26.1,0.04,27.68,2.963798
4,4,4,ioos:station:wmo:42043:1,2017-06-07 02:00:00+00:00,28.9818,-94.9186,1006.60,26.0,0.04,27.52,2.997866
...,...,...,...,...,...,...,...,...,...,...,...
22013,1435,1435,ioos:station:TABS:X:1,2017-09-30 21:30:00+00:00,27.0660,-96.3383,1013.73,0.0,32.48,29.05,0.000000
22014,1436,1436,ioos:station:TABS:X:1,2017-09-30 22:00:00+00:00,27.0660,-96.3383,1013.96,0.0,32.47,29.05,0.000000
22015,1437,1437,ioos:station:TABS:X:1,2017-09-30 22:30:00+00:00,27.0660,-96.3383,1014.23,0.0,32.49,29.04,0.000000
22016,1438,1438,ioos:station:TABS:X:1,2017-09-30 23:00:00+00:00,27.0660,-96.3383,1014.28,0.0,32.54,29.03,0.000000
22017,1439,1439,ioos:station:TABS:X:1,2017-09-30 23:30:00+00:00,27.0660,-96.3383,1014.38,0.0,32.56,29.00,0.000000

In [8]:
Hurc_df.nunique()

Unnamed: 0                       1488
Unnamed: 0.1                     1488
sensor                              6
date                             8404
latitude                            6
longitude                           6
air_pressure(mBar)               1842
air_temperature                   239
sea_water_practical_salinity     2663
sea_water_temperature             612
wind_speed                      14259
dtype: int64

In [6]:

SWater_Temp = Hurc_df("sea water temperature")
#Date = md.
plt.plot(xAxis, yAxis )
plt.title('Surface Water Temperature')
plt.xlabel('Date')
plt.ylabel('Surface Water Temp')
plt.show()

TypeError: 'DataFrame' object is not callable